---
version: '3'

services:

  backend:
    build:
      context: ./backend
      dockerfile: 'Dockerfile'
    image: ghcr.io/magfest/tuber-backend:latest
    restart: always
    links:
      - postgres:postgres
      - redis:redis
    environment:
      DATABASE_URL: postgresql://tuber:tuber@postgres/tuber
      REDIS_URL: redis://redis:6379/0
      VERBOSE: "true"
      FLASK_ENV: development
      WORKERS: 4
      CIRCUITBREAKER_THREADS: 4
    depends_on:
      - postgres
    networks:
      - tuber

  frontend:
    build:
      context: ./frontend
      dockerfile: 'Dockerfile'
    image: ghcr.io/magfest/tuber-frontend:latest
    restart: always
    links:
      - backend:tuber-backend
      - redis:redis
    depends_on:
      - backend
    networks:
      - tuber

  postgres:
    image: postgres:alpine
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=tuber
      - POSTGRES_USER=tuber
      - POSTGRES_DB=tuber
    networks:
      - tuber


  redis:
    image: redis:alpine
    restart: always
    networks:
      - tuber

  nginx:
    image: nginx:stable-alpine
    ports:
      - "8081:80"
    volumes:
      - ./contrib/nginx.conf:/etc/nginx/nginx.conf:ro
    links:
      - frontend:tuber-frontend
    networks:
      - tuber

networks:
  tuber:

volumes:
  db-data: